# Generated by Django 3.1.7 on 2021-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinenotes', '0002_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingnotes',
            field=models.FileField(upload_to='files/'),
        ),
    ]
