# Generated by Django 3.1.7 on 2021-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinenotes', '0005_auto_20210730_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingnotes',
            field=models.FileField(upload_to='media/files/'),
        ),
    ]
