# Generated by Django 3.1.7 on 2021-07-30 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlinenotes', '0008_auto_20210731_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 20, 1, 21, 857190, tzinfo=utc)),
        ),
    ]
