# Generated by Django 3.1.7 on 2021-08-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinenotes', '0014_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
